config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root 'main#show'
  get '/subscriber' => 'subscribe#feed', as: :subscriber
  get '/stream'     => 'stream#call',    as: :stream

  mount Sidekiq::Web, at: '/sidekiq'

end

app/models/publisher.rb
class Publisher
  class << self

    def publish(channel_name, message)
      if CHANNEL_LIST.include?(channel_name) && message.present?
        $redis.publish channel_name, message
      else
        raise "Unrecognized channel name or Empty message"
      end
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def show
  end
  
end

app/controllers/stream_controller.rb
class StreamController < ApplicationController

  def call
    if protected_params[:track].present?
      @track_key = protected_params[:track]

      generate_oauth_header
      init_publisher
    end

    render nothing: true
  end

  private

  def generate_oauth_header
    @oauth_header = SingleUserOauth.generate_header( oauth_params )
  end

  # Spawing background worker
  def init_publisher
    PublisherWorker.perform_async( publisher_params )
  end

  def oauth_params
    {
      request_method: GET,
      requested_url: 'https://stream.twitter.com/1.1/statuses/filter.json',
      query_params: {
        track: @track_key
      },
      oauth_consumer_key:    Rails.application.secrets.oauth_consumer_key,
      oauth_token:           Rails.application.secrets.oauth_token,
      oauth_consumer_secret: Rails.application.secrets.oauth_consumer_secret,
      oauth_access_secret:   Rails.application.secrets.oauth_access_secret
    }
  end

  def publisher_params
    {
      oauth_header: @oauth_header,
      track_key:    @track_key
    }
  end

  # Whitelisting the params
  def protected_params
    params.permit(:track)
  end

end

app/controllers/subscribe_controller.rb
class SubscribeController < ApplicationController
  include ActionController::Live

  def feed
    response.headers['Content-Type'] = 'text/event-stream'

    $redis.subscribe(TWITTER_CHANNEL) do |on|
      on.message do |channel, msg|
        response.stream.write "data: #{msg}\n\n"
      end
    end
  rescue ActionController::Live::ClientDisconnected
    logger.info "*** Client Disconnected ***"
  ensure
    response.stream.close
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Influx</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id='main-body'>

<%= yield %>

</body>
</html>

app/views/main/show.html.erb
<div id='track_key'>
  <%= form_tag(stream_path, remote: true, method: :get) do %>
    <%= text_field_tag :track, params[:track], placeholder: 'Track Keywords', autocomplete: 'off', required: true %>
    <%= submit_tag "Track" %>
  <% end %>

  <br>
  <input type="text" id="total_count" placeholder= 'Total Count', disabled>

</div>